### ISSUE TITLE
The character '&' breaks !lookup

### ISSUE THREAD

**Issue by uberj** [hamperbot/hamper#44]
```
    #uberj uberj!uberj@moz-AD308AD7.members.linode.com !lookup &
    Traceback (most recent call last):
      File "/home/wesley/hamper/hamper/commander.py", line 339, in runPlugins
        stop = getattr(plugin, func)(protocol, *args)
      File "/home/wesley/hamper/hamper/interfaces.py", line 81, in message
        stop = cmd.message(bot, comm)
      File "/home/wesley/hamper/hamper/interfaces.py", line 123, in message
        self.command(bot, comm, match.groups())
      File "/home/wesley/hamper/hamper/plugins/dictionary.py", line 55, in command
        gr = json.loads(gr)
      File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
        return _default_decoder.decode(s)
      File "/usr/lib/python2.7/json/decoder.py", line 368, in decode
        raise ValueError(errmsg("Extra data", s, end, len(s))) 
```

**Comment by justinnoah** [comment]
Closing as the (unofficial) Google Dictionary API hasn't been around for a while.
